openapi: 3.0.3
paths:
components:
  schemas:
    DogEnum:
      type: string
      enum: [ 'DOG_A', 'DOG_B' ]
    Dog:
      allOf:
        - $ref: './pet.yml#/components/schemas/PetBase'
        - properties:
            fluffy:
              type: boolean
            breed:
              $ref: '#/components/schemas/DogEnum'

